import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: ['src/index.ts', 'src/browser.ts', 'src/shim.ts', 'src/server-shim.ts', 'src/server-entry-shim.ts', 'src/vite.ts', 'src/cleanup.ts'],
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  deps: {
    neverBundle: [
      '@tanstack/react-router',
      '@tanstack/react-start',
      '@tanstack/router-plugin',
      '@tanstack/start-client-core',
      '@tanstack/start-fn-stubs',
      '@tanstack/start-server-core',
      '@tanstack/start-storage-context',
      '@tanstack/router-core',
      '@tanstack/router-core/ssr/server',
      'h3-v2',
      'cookie-es',
      '@testing-library/react',
      'vite',
      'react',
      'react-dom',
      'react-dom/client',
      'react-dom/server',
      'react/jsx-runtime',
      'vitest',
      '@tanstack-router-testing/react-router-testing',
      '@tanstack-router-testing/react-router-testing/cleanup',
    ],
  },
});
